name: Test

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on: [ pull_request ]
jobs:
  test:
    runs-on: macos-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: gradle
      - name: Install Arkana
        run: gem install arkana
      - name: Run Arkana
        env:
          PrivateKey: '<BASE64_STRING_OF_PEM_FILE>'
          TeamId: '<APPLE_STORE_TEAM_ID>'
          KeyId: '<MUSIC_SERVICE_KEY_ID>'
          LastFMAPIKey: '<LAST_FM_KEY>'
          LastFMAPISecret: '<LAST_FM_KEY>'
        run: arkana -l kotlin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run tests
        run: ./gradlew testAndroid iosSimulatorArm64Test
      - name: Publish Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./shared/build/test-results
      - name: Annotate Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          comment: 'true'
          include_passed: 'true'
